const weaponPresets = {
    "normal": {
        "name": "Normal",
        "color": "#00ff00",
        "bulletSpeed": 8,
        "fireRate": 150,
        "bulletSize": { "w": 4, "h": 12 },
        "damage": 10
    },
    "spread": {
        "name": "Spread",
        "color": "#00ffff",
        "bulletSpeed": 7,
        "fireRate": 200,
        "bulletSize": { "w": 6, "h": 6 },
        "damage": 7,
        "spread": 20,
        "rayCount": 3
    },
    "beam": {
        "name": "Beam",
        "color": "#ffff00",
        "bulletSpeed": 15,
        "fireRate": 80,
        "bulletSize": { "w": 2, "h": 20 },
        "damage": 5,
        "piercing": true
    },
    "plasma": {
        "name": "Plasma",
        "color": "#ff00ff",
        "bulletSpeed": 6,
        "fireRate": 120,
        "bulletSize": { "w": 10, "h": 10 },
        "damage": 15,
        "explode": true,
        "explosionRadius": 30,
        "explosionDamage": 10
    },
    "wave": {
        "name": "Wave",
        "color": "#ffffff",
        "bulletSpeed": 5,
        "fireRate": 250,
        "bulletSize": { "w": 12, "h": 4 },
        "damage": 8,
        "wave": true,
        "waveAmp": 10,
        "waveFreq": 0.1
    },
    "flame": {
        "name": "Flame",
        "color": "#ff6600",
        "bulletSpeed": 9,
        "fireRate": 90,
        "bulletSize": { "w": 8, "h": 16 },
        "damage": 6,
        "burn": true,
        "burnDamage": 5,
        "lifetime": 1000
    },
    "laser": {
        "name": "Laser",
        "color": "#ff0000",
        "bulletSpeed": 25,
        "fireRate": 50,
        "bulletSize": { "w": 1, "h": 30 },
        "damage": 8,
        "piercing": true,
        "beam": true
    },
    "rocket": {
        "name": "Rocket",
        "color": "#cccccc",
        "bulletSpeed": 4,
        "fireRate": 500,
        "bulletSize": { "w": 8, "h": 18 },
        "damage": 25,
        "explode": true,
        "explosionRadius": 50,
        "explosionDamage": 20,
        "homing": true
    },
    "pulse": {
        "name": "Pulse",
        "color": "#6600ff",
        "bulletSpeed": 12,
        "fireRate": 180,
        "bulletSize": { "w": 12, "h": 12 },
        "damage": 12,
        "pulse": true,
        "pulseRadius": 20,
        "pulseSpeed": 0.2
    },
    "vortex": {
        "name": "Vortex",
        "color": "#000000",
        "bulletSpeed": 2,
        "fireRate": 800,
        "bulletSize": { "w": 20, "h": 20 },
        "damage": 50,
        "pull": true,
        "pullRadius": 100,
        "lifetime": 5000
    },
    "afterburner": {
        "name": "Afterburner",
        "color": "#ff3300",
        "bulletSpeed": 10,
        "fireRate": 130,
        "bulletSize": { "w": 5, "h": 15 },
        "damage": 9,
        "trail": true,
        "trailLength": 10,
        "burn": true,
        "burnDamage": 3
    },
    "frostbite": {
        "name": "Frostbite",
        "color": "#00ccff",
        "bulletSpeed": 7,
        "fireRate": 160,
        "bulletSize": { "w": 7, "h": 7 },
        "damage": 8,
        "freeze": true,
        "freezeDuration": 1000
    },
    "venom": {
        "name": "Venom",
        "color": "#00ff33",
        "bulletSpeed": 9,
        "fireRate": 140,
        "bulletSize": { "w": 4, "h": 8 },
        "damage": 5,
        "poison": true,
        "poisonDuration": 3000
    },
    "shocker": {
        "name": "Shocker",
        "color": "#ffff66",
        "bulletSpeed": 12,
        "fireRate": 110,
        "bulletSize": { "w": 3, "h": 10 },
        "damage": 7,
        "stun": true,
        "stunDuration": 300
    },
    "magnet": {
        "name": "Magnet",
        "color": "#ff66cc",
        "bulletSpeed": 5,
        "fireRate": 220,
        "bulletSize": { "w": 10, "h": 10 },
        "damage": 6,
        "magneticPull": true,
        "magneticRange": 80
    },
    "ricochet": {
        "name": "Ricochet",
        "color": "#cc9900",
        "bulletSpeed": 10,
        "fireRate": 130,
        "bulletSize": { "w": 5, "h": 5 },
        "damage": 9,
        "ricochet": true,
        "richochetCount": 3
    },
    "splitter": {
        "name": "Splitter",
        "color": "#99ff66",
        "bulletSpeed": 8,
        "fireRate": 190,
        "bulletSize": { "w": 9, "h": 9 },
        "damage": 11,
        "split": true,
        "splitCount": 2
    },
    "bouncer": {
        "name": "Bouncer",
        "color": "#ff99cc",
        "bulletSpeed": 7,
        "fireRate": 170,
        "bulletSize": { "w": 8, "h": 8 },
        "damage": 8,
        "bounce": true,
        "bounceCount": 4
    },
    "teleporter": {
        "name": "Teleporter",
        "color": "#cc66ff",
        "bulletSpeed": 15,
        "fireRate": 100,
        "bulletSize": { "w": 6, "h": 6 },
        "damage": 10,
        "phaseShift": true,
        "phaseDistance": 50
    },
    "chain": {
        "name": "Chain",
        "color": "#ffcc66",
        "bulletSpeed": 9,
        "fireRate": 150,
        "bulletSize": { "w": 4, "h": 4 },
        "damage": 6,
        "electricChain": true,
        "chainLength": 4,
        "chainDistance": 60
    },
    "gravity": {
        "name": "Gravity",
        "color": "#999999",
        "bulletSpeed": 6,
        "fireRate": 210,
        "bulletSize": { "w": 12, "h": 12 },
        "damage": 14,
        "gravityAffect": 2
    },
    "frictionless": {
        "name": "Frictionless",
        "color": "#e6e6e6",
        "bulletSpeed": 11,
        "fireRate": 140,
        "bulletSize": { "w": 5, "h": 10 },
        "damage": 9,
        "friction": 1
    },
    "timewarp": {
        "name": "Time Warp",
        "color": "#66ffff",
        "bulletSpeed": 4,
        "fireRate": 300,
        "bulletSize": { "w": 8, "h": 8 },
        "damage": 7,
        "timeWarp": true,
        "warpFactor": 0.5
    },
    "slowmo": {
        "name": "Slow-Mo",
        "color": "#ffffcc",
        "bulletSpeed": 15,
        "fireRate": 80,
        "bulletSize": { "w": 4, "h": 14 },
        "damage": 8,
        "slowMotion": true,
        "slowFactor": 2
    },
    "crits": {
        "name": "Crits",
        "color": "#ff3333",
        "bulletSpeed": 10,
        "fireRate": 120,
        "bulletSize": { "w": 6, "h": 6 },
        "damage": 5,
        "crit": true,
        "critChance": 0.2,
        "critMultiplier": 3
    },
    "lifesteal": {
        "name": "Lifesteal",
        "color": "#cc0000",
        "bulletSpeed": 8,
        "fireRate": 160,
        "bulletSize": { "w": 7, "h": 12 },
        "damage": 7,
        "absorb": true,
        "absorbHeal": 2
    },
    "spawner": {
        "name": "Spawner",
        "color": "#ffffff",
        "bulletSpeed": 6,
        "fireRate": 400,
        "bulletSize": { "w": 10, "h": 10 },
        "damage": 10,
        "spawnOnHit": true,
        "spawnType": "normal",
        "spawnCount": 2,
        "spawnDelay": 200
    },
    "ghost": {
        "name": "Ghost",
        "color": "#cccccc",
        "bulletSpeed": 9,
        "fireRate": 130,
        "bulletSize": { "w": 5, "h": 15 },
        "damage": 8,
        "afterImage": true,
        "afterImageCount": 4,
        "afterImageDelay": 60
    },
    "cursed": {
        "name": "Cursed",
        "color": "#330033",
        "bulletSpeed": 7,
        "fireRate": 180,
        "bulletSize": { "w": 8, "h": 8 },
        "damage": 12,
        "cursed": true,
        "cursedDebuff": "damage"
    },
    "blessed": {
        "name": "Blessed",
        "color": "#ffff99",
        "bulletSpeed": 9,
        "fireRate": 150,
        "bulletSize": { "w": 6, "h": 12 },
        "damage": 9,
        "blessed": true,
        "blessedBuff": "defense"
    },
    "chaos": {
        "name": "Chaos",
        "color": "#ff00ff",
        "bulletSpeed": 10,
        "fireRate": 100,
        "bulletSize": { "w": 10, "h": 10 },
        "damage": 15,
        "chaosEffectClass": "chaos-spin",
        "randomTracking": () => Math.random() > 0.8,
        "randomSpin": () => Math.random() > 0.5,
        "randomColor": () => ['#ff00ff', '#00ff00', '#ffff00', '#ff0000', '#00ffff', '#ff6600', '#00ff99', '#ff1493', '#00ced1', '#32cd32', '#ff4500', '#1e90ff', '#ffd700', '#ff69b4', '#00bfff', '#7fff00', '#adff2f', '#ff7f50', '#dc143c', '#00008b'][Math.floor(Math.random() * 20)],
        "randomOffset": () => ({ "x": Math.random() * 80 - 40, "y": Math.random() * 50 - 25 }),
        "randomAlpha": () => Math.random() * 0.9 + 0.2,
        "randomVelocity": () => Math.random() * 2 + 0.4,
        "randomJitter": () => Math.random() * 10,
        "randomWave": () => Math.random() > 0.9,
        "randomDrift": () => Math.random() * 4.5,
        "randomMagnetism": () => (Math.random() * 8) > 0.75,
        "randomRotation": () => Math.random() * 360,
        "randomTrail": () => Math.floor(Math.random() * 20) + Math.PI,
        "randomGlitch": () => Math.random() > 0.75,
        "randomShockWave": () => Math.random() > 0.85,
        "randomPulse": () => Math.random() > 0.8,
        "randomMerge": () => Math.random() > 0.95,
        "randomFractal": () => Math.random() > 0.9,
        "randomStatic": () => Math.random() > 0.8,
        "randomScale": () => Math.random() * 2 + 0.6
    }
};
